language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -U pip setuptools
  - pip install .[dev]
script: coverage run --source maps setup.py test
after_success: codecov
